<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HeroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('heroes')->insert([
            [
                'name_en' => 'Hero Slider',
                'name_ar' => 'بطل الشريحة',
                'title_en' => 'Welcome to Our Platform',
                'title_ar' => 'مرحبًا بكم في منصتنا',
                'description_en' => 'This is a hero slider for the main page.',
                'description_ar' => 'هذه شريحة البطل للصفحة الرئيسية.',
                'image1' => 'hero_image1.jpg',
                'image2' => 'hero_image2.jpg',
                'video' => 'hero_video.mp4',
                'section' => 'Slider',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'About Us Section',
                'name_ar' => 'قسم من نحن',
                'title_en' => 'What Are tech touch',
                'title_ar' => 'حول رحلتنا',
                'description_en' => 'Lorem Ipsum Dolor Sit Amet, Consetetur Sadipscing Elitr, Sed Diam Nonumy Eirmod Tempor Invidunt Ut Labore Et Dolore Magna Aliquyam Erat, Sed Diam Voluptua. At Vero Eos Et Accusam Et Justo Duo Dolores Et Ea Rebum. Stet Clita Kasd Gubergren, No Sea Takimata Sanctus Est Lorem Ipsum Dolor Sit Amet. Lorem Ipsum Dolor Sit Amet, Consetetur Sadipscing Elitr, Sed Diam Nonumy Eirmod Tempor Invidunt Ut Labore Et Dolore Magna Aliquyam Erat, Sed Diam Voluptua. At Vero Eos Et Accusam Et Justo Duo Dolores Et Ea Rebum. Stet Clita Kasd Gubergren, No Sea Takimata Sanctus Est Lorem Ipsum Dolor Sit Amet.
                                    Lorem Ipsum Dolor Sit Amet, Consetetur Sadipscing Elitr, Sed Diam Nonumy Eirmod Tempor Invidunt Ut Labore Et Dolore Magna Aliquyam Erat, Sed Diam Voluptua. At Vero Eos Et Accusam Et Justo',
                'description_ar' => 'تعرف على قصتنا وقيمنا.',
                'image1' => 'about_image1.jpg',
                'image2' => null,
                'video' => null,
                'section' => 'About',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'services',
                'name_ar' => 'خدماتنا',
                'title_en' => 'The Best Service We Offer',
                'title_ar' => 'ما الذي نقدمه',
                'description_en' => 'Lorem Ipsum Dolor Sit Amet, Consetetur Sadipscing Elitr, Sed Diam Nonumy Eirmod Tempor Invidunt Ut Labore Et Dolore Magna Aliquyam Erat, Sed Diam Voluptua. At Vero Eos Et Accusam Et Justo Duo Dolores Et Ea Rebum. Stet Clita Kasd Gubergren, No Sea Takimata Sanctus Est Lorem Ipsum Dolor Sit Amet. Lorem Ipsum Dolor Sit Amet, Consetetur Sadipscing Elitr, Sed Diam Nonumy Eirmod Tempor Invidunt Ut Labore Et Dolore Magna Aliquyam Erat',
                'description_ar' => 'اكتشف مجموعة الخدمات التي نقدمها.',
                'image1' => null,
                'image2' => null,
                'video' => null,
                'section' => 'Services',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Our Files',
                'name_ar' => 'خدماتنا',
                'title_en' => 'The Secret To Success May Be Inside One Of The Files',
                'title_ar' => 'ما الذي نقدمه',
                'description_en' => 'Explore the range of services we provide.',
                'description_ar' => 'اكتشف مجموعة الخدمات التي نقدمها.',
                'image1' => 'images/1733522744 - files_home.png.png',
                'image2' => 'images/1733522744 - files_home.png.png',
                'video' => null,
                'section' => 'Files',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Tech Touch',
                'name_ar' => 'خدماتنا',
                'title_en' => 'partners',
                'title_ar' => 'ما الذي نقدمه',
                'description_en' => 'Lorem Ipsum Dolor Sit Amet, Consetetur Sadipscing Elitr, Sed Diam Nonumy Eirmod Tempor Invidunt Ut Labore Et Dolore Magna Aliquyam Erat',
                'description_ar' => 'اكتشف مجموعة الخدمات التي نقدمها.',
                'image1' => 'services_image1.jpg',
                'image2' => 'services_image2.jpg',
                'video' => null,
                'section' => 'Partners',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Work',
                'name_ar' => 'خدماتنا',
                'title_en' => 'Improve & Enhance the Tech Projects',
                'title_ar' => 'ما الذي نقدمه',
                'description_en' => 'Explore the range of services we provide.',
                'description_ar' => 'اكتشف مجموعة الخدمات التي نقدمها.',
                'image1' => 'services_image1.jpg',
                'image2' => 'services_image2.jpg',
                'video' => null,
                'section' => 'Works',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'OUR TEAM',
                'name_ar' => 'خدماتنا',
                'title_en' => 'Meet Our Team',
                'title_ar' => 'ما الذي نقدمه',
                'description_en' => 'Lorem Ipsum Dolor Sit Amet, Consetetur Sadipscing Elitr, Sed Diam Nonumy Eirmod Tempor Invidunt Ut Labore Et Dolore Magna Aliquyam Erat',
                'description_ar' => 'اكتشف مجموعة الخدمات التي نقدمها.',
                'image1' => 'services_image1.jpg',
                'image2' => 'services_image2.jpg',
                'video' => null,
                'section' => 'Teams',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Our Services',
                'name_ar' => 'خدماتنا',
                'title_en' => 'What We Offer',
                'title_ar' => 'ما الذي نقدمه',
                'description_en' => 'Explore the range of services we provide.',
                'description_ar' => 'اكتشف مجموعة الخدمات التي نقدمها.',
                'image1' => 'services_image1.jpg',
                'image2' => 'services_image2.jpg',
                'video' => null,
                'section' => 'Feedback',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Our Services',
                'name_ar' => 'خدماتنا',
                'title_en' => 'What We Offer',
                'title_ar' => 'ما الذي نقدمه',
                'description_en' => 'Explore the range of services we provide.',
                'description_ar' => 'اكتشف مجموعة الخدمات التي نقدمها.',
                'image1' => 'services_image1.jpg',
                'image2' => 'services_image2.jpg',
                'video' => null,
                'section' => 'Goals',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_en' => 'Our Services',
                'name_ar' => 'خدماتنا',
                'title_en' => 'What We Offer',
                'title_ar' => 'ما الذي نقدمه',
                'description_en' => 'Explore the range of services we provide.',
                'description_ar' => 'اكتشف مجموعة الخدمات التي نقدمها.',
                'image1' => 'services_image1.jpg',
                'image2' => 'services_image2.jpg',
                'video' => null,
                'section' => 'Features',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
